### ISSUE TITLE
Convert to a package

### ISSUE THREAD

**Issue by cenkalti** [br0xen/boltbrowser#26]
@br0xen I am using boltdb in one of my projects and I like boltbrowser. I would like to embed boltbrowser into my application binary. To do this, I need to be able to import it as a package. Current package name (`main`) does not allow me to that. I propose to move all code files except `boltbrowser.go` into a new package under `github.com/br0xen/boltbrowser/boltbrowser`. This will not break backwards compatibility and will allow other packages to import boltbrowser as a library. I can send you a PR if it's okay. Are you happy with this change?

**Comment by br0xen** [comment]
So, a couple of thoughts about this:
- If I switch this to be a package, along with that comes an expectation of supporting it as a package, I currently don't have the time or desire to do that... Changing any exported things could break any packages that are importing it, then I have to deal with that...
- I've built everything to be coupled to `package main`, I'm not sure what all would be required to change that.

Having said all that, it's open source, feel free to grab it and use it however you want!

**Comment by cenkalti** [comment]
Hey @br0xen, I know this issue is quite old (and closed!), but I wanted to revisit it because boltbrowser has been incredibly useful in my projects over the years - really appreciate the work you've put into it.

I completely understood your concerns back in 2018 about the maintenance burden of supporting it as a package. I'm still using boltbrowser in production and maintaining a fork to make it importable, but I wanted to see if you'd reconsider a very minimal change:

**What I'm proposing:**
- Move the existing code into a `boltbrowser` package
- Keep only `main.go` in the root (CLI users see zero change)
- Export a single function: `func Browse(db *bolt.DB)`
- No other API surface - just this one function

**Why this might work now:**
- Minimal API surface = minimal maintenance burden for you
- Zero impact on CLI functionality
- I'm happy to submit a clean PR with atomic commits you can review individually
- Would help projects like mine avoid maintaining forks

I totally get it if you still prefer to keep things as-is after all these years - it's your project and I respect whatever you decide. If not, I'll just keep using my fork, no worries at all. 

FWIW, I've contributed to the bbolt project in the past (https://github.com/etcd-io/bbolt/commits?author=cenkalti), so I'm familiar with the codebase and ecosystem.

Thanks again for building such a solid tool that's still going strong 7 years later!

**Comment by br0xen** [comment]
Hey @cenkalti !
Sorry it took me so long to respond to this. I've been thinking this over and, honestly, I don't hate the idea. Boltbrowser has (obviously) not been updated in quite some time, and still gets everything done that I need it to when I pull it up, as long as any changes you're proposing don't change that, I'm ok with it. 😀

If you'd like to submit a PR to make this change, I'll happily review it and get it merged in.

Thanks!

**Comment by cenkalti** [comment]
# Package Structure Question

Hey @br0xen! Before I start working on the PR, I wanted to get your input on the package structure since there are trade-offs between different approaches.

I see two main options:

## Option 1: Library at Root (Standard Go Layout)

```
github.com/br0xen/boltbrowser/
├── browser.go, model.go, etc. (package boltbrowser)
└── cmd/boltbrowser/main.go (package main)
```

- **Import:** `import "github.com/br0xen/boltbrowser"`
- **Install:** `go get github.com/br0xen/boltbrowser/cmd/boltbrowser`

**This is the standard Go project layout**, gives the cleanest import path, but **changes the install command**. Your README would need updating from:
```bash
go get github.com/br0xen/boltbrowser
```
to:
```bash
go get github.com/br0xen/boltbrowser/cmd/boltbrowser
```

## Option 2: Library in Subdirectory (Zero Breaking Changes)

```
github.com/br0xen/boltbrowser/
├── main.go (package main)
└── boltbrowser/
    ├── browser.go, model.go, etc. (package boltbrowser)
```

- **Import:** `import "github.com/br0xen/boltbrowser/boltbrowser"`
- **Install:** `go install github.com/br0xen/boltbrowser@latest` (unchanged)

**This preserves backward compatibility** - the install command, README, and any existing user scripts continue to work unchanged. The import path has a repeated name, but it's a minor cosmetic thing.

## My Recommendation

I'd suggest **Option 2** because:
1. Zero breaking changes for CLI users (the primary use case for 7 years)
2. No README/docs updates needed
3. The slightly awkward import path is a small price for backward compatibility
4. Since this is primarily a CLI tool being made importable (not the other way around), having the library in a subdirectory makes sense

But I'm happy to do whichever you prefer! Let me know which approach you'd like and I'll submit a clean PR with atomic commits.

Thanks!

**Comment by br0xen** [comment]
I agree with you, Option 2 sounds like a good plan.
Thanks!
