### ISSUE TITLE
Update boltdb import path

### ISSUE THREAD

**Issue by cenkalti** [br0xen/boltbrowser#27]
https://github.com/br0xen/boltbrowser/blob/7d7e0bfcd3ce4f1bc89c85854490bc822e7857b3/boltbrowser.go#L10

The original project is not maintained anymore. Author recommends to use the fork at https://github.com/coreos/bbolt.

https://github.com/boltdb/bolt#a-message-from-the-author

**Comment by br0xen** [comment]
The author stated that the project is complete and only recommends using `bbolt` if you're looking for more features. `boltbrowser` is a browser for `bolt` databases.

It'd be perfectly reasonable to fork this project to create a new application which is built for `bbolt` databases, but at this moment I don't have a compelling reason to do so. You can feel free though, I likely wouldn't merge it into this repo, as it serves a different purpose.
