### ISSUE TITLE
Exported files not closed correctly

### ISSUE THREAD

**Issue by mdavey** [br0xen/boltbrowser#30]
When using the 'X' hotkey to export, you are prompted for a filename and the data is saved correctly.

However the file isn't closed  (it cannot be opened by another process until you exit boltbrowser)

The next time a export is performed, the entered filename isn't used, and data appears to be appended to the original file  (which is still open).

OS:  Windows 10
Version: Most recent from readme.md link

**Comment by br0xen** [comment]
Thanks, it should be fixed now.
