### ISSUE TITLE
[Crash] boltbrowser crashes if the db has values stored in root

### ISSUE THREAD

**Issue by pyed** [br0xen/boltbrowser#44]
it's probably not a good idea to store values in the root bucket, but shouldn't boltbrowser account for that ?

the following code generates a boltdb `boltbrowser` can't open
```go
func main() {
	db, err := bolt.Open("crash.db", 0600, nil)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	db.Update(func(tx *bolt.Tx) error {
		return tx.Cursor().Bucket().Put([]byte("boat"), []byte("I'm on a root!"))
	})

	db.View(func(tx *bolt.Tx) error {
		fmt.Printf("%s\n", tx.Cursor().Bucket().Get([]byte("boat")))
		return nil
	})
}
```

**Comment by br0xen** [comment]
I guess I've never run into this... You're right it definitely shouldn't just crash. When I get a chance, I'll see what I can do, unless anyone else wants to submit a PR for it? ;-)

**Comment by br0xen** [comment]
I just pushed a commit which should take care of this. 
Boltbrowser still doesn't let you _create_ databases like this, it'll ask for a root bucket when you open a new db... But if you open a db that was created elsewhere that allows it, you should be able to edit it. Let me know if you run into any issues.

**Comment by pyed** [comment]
Thank you for the quick fix, but there's a bug, consider the following code
``` go
func main() {
	db, err := bolt.Open("crash.db", 0600, nil)
	if err != nil {
		panic(err)
	}
	defer db.Close()

	db.Update(func(tx *bolt.Tx) error {
		b, _ := tx.CreateBucketIfNotExists([]byte("Top level bucket"))
		b.Put([]byte("node"), []byte("aval"))

		return tx.Cursor().Bucket().Put([]byte("boat"), []byte("I'm on a root!"))
	})
}
```

`boltbrowser` will show that db as:
```
  + Top level bucket                                                            
  -                                                                             
    - Top level bucket                                                          
      node: aval                                                                
    boat: I'm on a root!    
```

when it should be
```
  - Top level bucket
      node: aval                                                                                                        
  boat: I'm on a root!    
```

**Comment by br0xen** [comment]
OK, I pushed a new commit that treats that better. 
So, for ease of development and getting this fix out quickly, it's actually going to look like this:
```
-
  - Top level bucket
    node: aval
  boat: I'm on a root!
```
In this case I'm just making the 'root' of the DB a bucket, so you can collapse it all, if you want...

It could definitely be cleaned up more and maybe I'll do that at some point (or someone else can), but I don't have the time right now to do more, gotta get back to writing code that I actually get paid for. :P

**Comment by pyed** [comment]
I don't think your last push fixed it, still duplicates, but thanks for the effort.

**Comment by br0xen** [comment]
![image](https://user-images.githubusercontent.com/1273280/120213861-57dc3980-c1f9-11eb-9f7f-6c0faf7bd24c.png)
This is what I see when I open the DB created with your code in https://github.com/br0xen/boltbrowser/issues/44#issuecomment-851541860

**Comment by pyed** [comment]
Yes you're right, my bad I though I updated the binary, boltbrowser should have `-version` :p 

Thanks!

**Comment by br0xen** [comment]
No worries, and yeah, someone should add a `-version`. :)
