### ISSUE TITLE
Git Repository for prebuilt binaries has expired certificate

### ISSUE THREAD

**Issue by MooseOnTehLoose** [br0xen/boltbrowser#48]
While attempting to grab boltbrowser for linux (x64) I discovered that the letsencrypt cert for this URL has expired:

`wget -O boltbrowser https://git.bullercodeworks.com/attachments/29367198-79f9-4fb3-9a66-f71a0e605006
--2022-01-14 12:28:48--  https://git.bullercodeworks.com/attachments/29367198-79f9-4fb3-9a66-f71a0e605006
Resolving git.bullercodeworks.com (git.bullercodeworks.com)... 149.28.127.101
Connecting to git.bullercodeworks.com (git.bullercodeworks.com)|149.28.127.101|:443... connected.
ERROR: cannot verify git.bullercodeworks.com's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to git.bullercodeworks.com insecurely, use `--no-check-certificate'.
`

Is it possible to just release the binaries as part of a standard GitHub Release?

**Comment by br0xen** [comment]
When did you try this? I do not receive that error, and the certificate looks up to date to me.

I don't use github as my main source control location, which is why the releases aren't hosted on here... I'll see if I can find time to duplicate the process of building those releases here, but boltbrowser is ultimately just a hobby project of mine, so I unfortunately can't afford to prioritize it. 

Pulling the code and building yourself is always an option too.

**Comment by MooseOnTehLoose** [comment]
Oh literally just a few minutes ago on a Centos 7.9 machine.

**Comment by MooseOnTehLoose** [comment]
Ah, I found my issue:

I forgot about the letsencrypt cert expiring in september 2021, and after upgrading the ca-certificates package I am no longer getting the cert errors:

`Installed Packages
ca-certificates.noarch                           2020.2.41-70.0.el7_8                           @updates
Available Packages
ca-certificates.noarch                           2021.2.50-72.el7_9                             updates `


`wget -O boltbrowser https://git.bullercodeworks.com/attachments/29367198-79f9-4fb3-9a66-f71a0e605006
--2022-01-14 13:16:14--  https://git.bullercodeworks.com/attachments/29367198-79f9-4fb3-9a66-f71a0e605006
Resolving git.bullercodeworks.com (git.bullercodeworks.com)... 149.28.127.101
Connecting to git.bullercodeworks.com (git.bullercodeworks.com)|149.28.127.101|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3465446 (3.3M) [application/octet-stream]
Saving to: ‘boltbrowser’

100%[==============================================================>] 3,465,446   18.0MB/s   in 0.2s   

2022-01-14 13:16:14 (18.0 MB/s) - ‘boltbrowser’ saved [3465446/3465446]
`
