### ISSUE TITLE
how do i build this?

### ISSUE THREAD

**Issue by evnix** [br0xen/boltbrowser#5]
i tried this
```
$ go build boltbrowser.go 
# command-line-arguments
./boltbrowser.go:18: undefined: BoltDB
./boltbrowser.go:44: undefined: defaultStyle
./boltbrowser.go:47: undefined: mainLoop

```

**Comment by br0xen** [comment]
You have to install all of the dependencies for it.
Go makes this easy, you can just type 'go get -u <repo>' and it will download and install all dependencies for a project.

**Comment by evnix** [comment]
```
$ go get -u github.com/br0xen/boltbrowser
$ #  go build boltbrowser.go
command-line-arguments
./boltbrowser.go:18: undefined: BoltDB
./boltbrowser.go:44: undefined: defaultStyle
./boltbrowser.go:47: undefined: mainLoop
```
i have also installed boltdb prior to that command.

**Comment by br0xen** [comment]
When you are using the `go build boltbrowser.go` command, you are telling go to build only that file, not the complete project. What you actually want to do is just `go build` or `go install`.

I would recommend that you check out the [go documentation](https://golang.org/doc/), all of this is explained there.
