### ISSUE TITLE
Pre-built binaries link is broken

### ISSUE THREAD

**Issue by aniketnk** [br0xen/boltbrowser#58]
All pre-built binaries show `Not found`
Example: Linux 64-bit
https://git.bullercodeworks.com/attachments/29367198-79f9-4fb3-9a66-f71a0e605006
<img width="870" alt="image" src="https://user-images.githubusercontent.com/34034261/228809926-2048c37f-906a-455c-99aa-65eee9d861fc.png">

It was working a couple of months ago. This is the preferred method for using it on machines without `go` installed.

**Comment by br0xen** [comment]
I've updated the readme to reference the github 'Releases' page.
