### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by lrjbrual** [br0xen/boltbrowser#63]
This does not work, after installing in mac. I am using Sonama 14. 

`zsh: command not found: boltbrowser`

**Comment by br0xen** [comment]
This error would happen when the binary produced is not in your path. This isn't a problem with boltbrowser.

I don't work on a Mac, so I'm not 100% sure on the best way to get that done, but here is some info from the apple forums:
[Adding a directory to the PATH in macOS Monterey?](https://discussions.apple.com/thread/254226896?sortBy=best)
It's from MacOS 12, but hopefully it hasn't changed too much.
