### ISSUE TITLE
Error when key begins with "/"

### ISSUE THREAD

**Issue by happyalu** [br0xen/boltbrowser#8]
I happened to have an entry with the key="/e/210". When I browse that row, it doesn't allow me to rename/edit/delete it. It says "Not sure what to do here".

**Comment by br0xen** [comment]
I just pushed a new branch up called "unicode-paths". It's not a permanent solution, but see if it works for you. The main branch uses "/" as a character to split up paths on the display, which was trickling down and causing an error when a key/value actually had "/" in it... In the "unicode-paths" branch I changed that to "→". 

I'll work on  a more permanent solution when I can. :P Let me know if this solves the issue for you.

**Comment by happyalu** [comment]
That solved it! Thanks!

**Comment by br0xen** [comment]
:+1:

**Comment by br0xen** [comment]
This issue has been fixed as of Commit bbef34084878f24590bb5e280e96125f97f5746c
